<?php $page_title = " - Accueil"; ?>
<?php require_once "./src/inc/header.php"; ?>

    <div class="main__content">
        <section class="main__section">
            <form id="form">
                <input class="form__element form__element--clickable" type="text" name="subject" id="subject"
                       placeholder="subject">
                <input class="form__element form__element--clickable" type="text" name="email" id="email"
                       placeholder="email">
                <textarea class="form__element form__element--clickable" name="message" id="message"
                          placeholder="message"></textarea>
                <div class="send">
                    <div id="form_loading">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                             style="margin: auto; background: none; display: block; shape-rendering: auto;"
                             width="200px"
                             height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                            <circle cx="50" cy="50" fill="none" stroke="#c4c4c4" stroke-width="10" r="35"
                                    stroke-dasharray="164.93361431346415 56.97787143782138">
                                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite"
                                                  dur="2.7027027027027026s" values="0 50 50;360 50 50"
                                                  keyTimes="0;1"></animateTransform>
                            </circle>
                            <!-- [ldio] generated by https://loading.io/ --></svg>
                    </div>
                    <input id="form_submit" class="form__element" type="submit" value="Envoyer">
                </div>

                <p id="info"></p>
            </form>
        </section>
    </div>


<?php require_once "./src/inc/footer.php"; ?>